/**
 * Location-aware Playwright runner.
 *
 * `LOCATION=CAN npm test`  -> one Playwright run for Canada (unchanged behaviour).
 * `npm test`               -> one run per location (USA, then CAN), producing a
 *                             SINGLE Allure report that covers both.
 *
 * Location is resolved at import time inside every spec (`getLocationConfig()`
 * at module scope), so a process can only ever represent one country. Covering
 * both therefore means one child Playwright process per location, with the
 * Allure results accumulated across passes and the HTML report built once at
 * the end:
 *   - pass 0 clears allure-results/desktop (normal globalSetup behaviour)
 *   - later passes set ALLURE_KEEP_RESULTS=1 so they append instead of wiping
 *   - every pass sets ALLURE_SKIP_REPORT=1; this script generates the report
 *
 * Any extra CLI arguments are forwarded verbatim to `playwright test`, so
 * `npm test -- --grep @smoke --project=Chrome` keeps working.
 */
import { spawnSync } from 'node:child_process';
import { getBrowserProjectKey } from '../config/browserSelection';
import process from 'node:process';
import { loadEnv, isCI } from '../config/env';
import { getLocationsToRun } from '../config/locations/locationConfig';
import generateAllureReport from './generate-allure-report';
import { REPO_ROOT } from './allurePaths';

loadEnv();

const PLAYWRIGHT_CLI = require.resolve('@playwright/test/cli');

/** Run `playwright test` for one location and return its exit code. */
function runLocation(location: string, index: number, total: number, args: string[]): number {
  const banner = total > 1 ? ` (pass ${index + 1} of ${total})` : '';
  console.log(`\n[locations] Running LOCATION=${location}${banner}\n`);

  const result = spawnSync(process.execPath, [PLAYWRIGHT_CLI, 'test', ...args], {
    cwd: REPO_ROOT,
    stdio: 'inherit',
    env: {
      ...process.env,
      LOCATION: location,
      LOCATION_PASS_INDEX: String(index),
      LOCATION_PASS_TOTAL: String(total),
      // Keep results from earlier passes so the final report covers them all.
      ALLURE_KEEP_RESULTS: index > 0 ? '1' : '',
      // Build the HTML report once, after the last pass — not per pass.
      ALLURE_SKIP_REPORT: '1',
    },
  });

  if (result.error) {
    console.error(`[locations] Failed to start Playwright for ${location}:`, result.error.message);
    return 1;
  }

  return result.status ?? 1;
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const locations = getLocationsToRun();

  // Deselect Chrome-only tests on firefox/webkit rather than reporting them as
  // skipped - "36 selected" is clearer than "42 passed, 6 skipped".
  if (
    getBrowserProjectKey() !== 'chromium' &&
    !args.some((arg) => arg.startsWith('--grep-invert'))
  ) {
    args.push('--grep-invert', '@chrome-only');
    console.log('[browser] Non-Chrome run — deselecting @chrome-only tests.');
  }

  if (locations.length > 1) {
    console.log(`[locations] No LOCATION set — running all locations: ${locations.join(', ')}`);
  }

  let exitCode = 0;
  for (const [index, location] of locations.entries()) {
    const status = runLocation(location, index, locations.length, args);
    // Keep going so the report covers every location even if one pass fails,
    // but surface the failure in this process's exit code.
    if (status !== 0) exitCode = status;
  }

  // Under CI the report is generated by an explicit workflow step (the same
  // reason playwright.config.ts disables globalTeardown there).
  if (!isCI) {
    await generateAllureReport('desktop');
    console.log('\n[allure] Report covers: ' + locations.join(', '));
    console.log('[allure] Open it with:  npm run allure:open\n');
  }

  process.exit(exitCode);
}

void main();
